api/urls.py
from django.conf.urls import url, include
from api.views import PostViewSet
from rest_framework.routers import DefaultRouter

router = DefaultRouter()
router.register(r'posts', PostViewSet)

urlpatterns = [
    url(r'^auth/', include('rest_framework.urls', namespace='rest_framework')),
]

urlpatterns += router.urls

blog/urls.py
from django.conf.urls import url
from blog import views

urlpatterns = [
    url(r'^post/(?P<pk>\d+)/comment/$', views.add_comment_to_post, name='add_comment_to_post'),
    url(r'^post/(?P<pk>\d+)/publish/$', views.post_publish, name='post_publish'),
    url(r'^post/(?P<pk>\d+)/$', views.post_detail, name='post_detail'),
    url(r'^post/new/$', views.post_new, name='post_new'),
    url(r'^post/(?P<pk>\d+)/edit/$', views.post_edit, name='post_edit'),
    url(r'^drafts/$', views.post_draft_list, name='post_draft_list'),
    url(r'^post/(?P<pk>\d+)/remove/$', views.post_remove, name='post_remove'),
    url(r'^comment/(?P<pk>\d+)/remove/$', views.comment_remove, name='comment_remove'),
    url(r'^comment/(?P<pk>\d+)/approve/$', views.comment_approve, name='comment_approve'),
    url(r'^$', views.post_list, name='post_list'),
]

blog/models.py
from django.conf import settings
from django.db import models
from django.utils import timezone

class Post(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL)
    title = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(
        default=timezone.now)
    published_date = models.DateTimeField(
        blank=True, null=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def approved_comments(self):
        return self.comments.filter(approved_comment=True)

    def __str__(self):
        return self.title


class Comment(models.Model):
    post = models.ForeignKey('blog.Post', related_name='comments')
    author = models.ForeignKey(settings.AUTH_USER_MODEL)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    approved_comment = models.BooleanField(default=False)

    def approve(self):
        self.approved_comment = True
        self.save()

    def __str__(self):
        return self.text


class HTMLField(models.TextField):
    pass

blog/forms.py
from django import forms
from .models import Post, Comment


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'text',)


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import  timezone
from .models import Post, Comment
from .forms import PostForm, CommentForm
from django.contrib.auth.decorators import login_required


def post_list(request):
    posts = Post.objects.filter(published_date__lte=timezone.now()).order_by('published_date')
    return render(request, 'blog/post_list.html', {'posts': posts})


def post_detail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    return render(request, 'blog/post_detail.html', {'post': post})


@login_required
def post_publish(request, pk):
    post = get_object_or_404(Post, pk=pk)
    post.publish()
    return redirect('post_detail', pk=pk)


@login_required
def post_new(request):
    if request.method == "POST":
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return redirect('post_detail', pk=post.pk)
    else:
        form = PostForm()
    return render(request, 'blog/post_new.html', {'form': form})


@login_required
def post_edit(request, pk):
    if request.method == "POST":
        post = get_object_or_404(Post, pk=pk)
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return redirect('post_detail', pk=post.pk)
    else:
        post = get_object_or_404(Post, pk=pk)
        form = PostForm(instance=post)
    return render(request, 'blog/post_edit.html', {'form': form})


@login_required
def post_draft_list(request):
    posts = Post.objects.filter(published_date__isnull=True).order_by('created_date')
    return render(request, 'blog/post_draft_list.html', {'posts': posts})


@login_required
def post_remove(request, pk):
    post = get_object_or_404(Post, pk=pk)
    post.delete()
    return redirect('post_list')


def add_comment_to_post(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.post = post
            comment.save()
            form.save_m2m()
            return redirect('post_detail', pk=post.pk)
    else:
        form = CommentForm()
    return render(request, 'blog/add_comment_to_post.html', {'form': form})


@login_required
def comment_remove(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    post_pk = comment.post.pk
    comment.delete()
    return redirect('post_detail', pk=post_pk)


@login_required
def comment_approve(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    comment.approve()
    return redirect('post_detail', pk=comment.post.pk)

blog/templates/blog/add_comment_to_post.html
{% extends 'blog/base.html' %}
{% load wysiwyg staticfiles %}
{% block extracss %}
    {{ block.super }}
    {% wysiwyg_setup %}
{% endblock extracss %}

{% block contentbody %}
    <h1>New comment</h1>
    <form method="POST" class="comment-form">
        {% csrf_token %}
        {{ form.non_field_errors }}
        <div class="form-group row">
            <label for="id_text" class="col-sm-2 col-form-label">Comment Text</label>
            <div class="col-sm-10">
                <textarea id="id_text"></textarea>
                {% wysiwyg_editor "id_text" editor_name="tinymce" %}
            </div>
        </div>
        <button class="save btn btn-default" type="submit">Save</button>
    </form>
{% endblock contentbody %}

blog/templates/blog/base.html
{% extends 'base.html' %}

{% block navlinks %}
    <li class="nav-item">
        <a href="{% url 'post_list' %}" class="nav-link">Posts</a>
    </li>
    <li class="nav-item">
        <a href="{% url 'post_draft_list' %}" class="nav-link">Drafts</a>
    </li>
{% endblock navlinks %}

{% block content %}
    <div class="row">
        <a href="{% url 'post_new' %}" class="btn btn-secondary"><span class="fa fa-plus-square"> New Post</span></a>
    </div>
    <hr>
    <div class="row">
        <div class="col-sm-8 blog-main">
        {% block contentbody %}
        {% endblock %}
        </div>
    </div>
{% endblock content %}
{% block extrajs %}
{% endblock extrajs %}

blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %}

{% block contentbody %}
    <div class="blog-post">
        <h2 class="blog-post-title">{{ post.title }}</h2>
        <p class="blog-post-meta">Created: {{ post.created_date }}</p>
        {% if post.published_date %}
            <p class="blog-post-meta">Published: {{ post.published_date }}</p>
        {% else %}
            <a href="{% url 'blog.views.post_publish' pk=post.pk %}" class="btn btn-primary">Publish</a>
        {% endif %}

        {% if user.is_authenticated %}
            <a href="{% url 'post_edit' pk=post.pk %}" class="btn btn-warning"><span class="fa fa-pencil"> Edit Post</span></a>
            <a href="{% url 'post_edit' pk=post.pk %}" class="btn btn-danger"><span
                    class="fa fa-trash-o"> Delete Post</span></a>
        {% endif %}
        <p class="blog-post-body">
            {{ post.text|safe }}
        </p>
    </div>
    <hr>
    <a class="btn btn-default" href="{% url 'add_comment_to_post' pk=post.pk %}">Add comment</a>
    {% for comment in post.comments.all %}
        {% if user.is_authenticated or comment.approved_comment %}
            <div class="comment">
                <div class="date">
                    {{ comment.created_date }}
                    {% if not comment.approved_comment %}
                        <a class="btn btn-danger" href="{% url 'comment_remove' pk=comment.pk %}"><span class="fa fa-trash-o"> Remove</span></a>
                        <a class="btn btn-success" href="{% url 'comment_approve' pk=comment.pk %}"><span class="fa fa-check-circle-o"> Approve</span></a>
                    {% endif %}
                </div>
                <strong>{{ comment.author }}</strong>
                <p>{{ comment.text|safe|linebreaks }}</p>
            </div>
        {% endif %}
    {% empty %}
        <p>No comments here yet :(</p>
    {% endfor %}

{% endblock contentbody %}

blog/templates/blog/post_draft_list.html
{% extends "blog/base.html" %}
{% block contentbody %}
    {% for post in posts %}
        <div class="blog-post">
            <h2 class="blog-post-title"><a href="{% url 'post_detail' pk=post.pk %}">{{ post.title }}</a></h2>
            <p class="blog-post-meta">Created: {{ post.created_date|date:'d-m-Y' }}</p>
            <p class="blog-post-body">
                {{ post.text|safe|truncatechars:200 }}
            </p>
        </div>
    {% endfor %}
{% endblock contentbody %}

blog/templates/blog/post_edit.html
{% extends 'blog/base.html' %}
{% load bootstrap4 tinymce %}
{% block contentbody %}
    <form role="form" class="form-horizontal"  method="post" name="new_post">
        {% csrf_token %}
        {% bootstrap_form form layout="horizontal" size="md" %}
        {% buttons submit='Save' reset='Cancel' layout='horizontal' %}{% endbuttons %}
    </form>
{% endblock contentbody %}
{% block extrajs %}
    {% add_tinymce_to_selector selector='#id_text' %}
{% endblock extrajs %}

blog/templates/blog/post_list.html
{% extends "blog/base.html" %}
{% block contentbody %}
    {% for post in posts %}
        <div class="blog-post">
            <h2 class="blog-post-title"><a href="{% url 'post_detail' pk=post.pk %}">{{ post.title }}</a></h2>
            <p class="blog-post-meta">Created: {{ post.created_date }}</p>
            <p class="blog-post-meta">Published: {{ post.published_date }}</p>
            <p class="blog-post-meta">Words: {{ post.text|wordcount }}</p>
            <p class="blog-post-body">
                {{ post.text|truncatechars_html:375 }}
            </p>
            <a href="{% url 'blog.views.post_detail' pk=post.pk %}">Comments: {{ post.approved_comments.count }}</a>
        </div>
    {% endfor %}
{% endblock contentbody %}

blog/templates/blog/post_new.html
{% extends 'blog/base.html' %}
{% load bootstrap4 tinymce %}
{% block contentbody %}
    <form role="form" class="form-horizontal" method="post" name="post_form">
        {% csrf_token %}
        {% bootstrap_form form layout="horizontal" size="md" %}
        {% buttons submit='Save' reset='Cancel' layout='horizontal' %}{% endbuttons %}
    </form>
{% endblock contentbody %}
{% block extrajs %}
    {% add_tinymce_to_selector selector='#id_text' %}
    <script type="text/javascript">
        $(document).ready(function() {
            $("button[type='submit']").click(function(e){
                e.preventDefault();
                tinymce.triggerSave();
                $('form').submit();
            });
        });
    </script>
{% endblock extrajs %}